# Generated by Django 4.2.5 on 2023-09-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время и дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время и дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время и дата удаления')),
                ('text', models.TextField(verbose_name='Тело сообщения (текст)')),
                ('telegram_chat_id', models.BigIntegerField(db_index=True, editable=False, verbose_name='Идентификатор пользователя в телеграме')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Кто написал')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
