# Generated by Django 4.2.5 on 2023-09-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='telegram_chat_id',
        ),
    ]
