# Generated by Django 4.2.5 on 2023-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время и дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время и дата обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время и дата удаления')),
                ('login', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=254, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, help_text='True - ваш акк активный, False - удален', verbose_name='Активность')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус менеджера')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-datetime_updated',),
            },
        ),
    ]
