# Generated by Django 4.2.5 on 2023-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Идентификатор чата'),
        ),
    ]
